# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.11.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: This repo holds addons developed to ease the development of REST
    services into Odoo.
repo_name: REST frameworks
repo_slug: rest-framework
repo_website: https://github.com/OCA/rest-framework
travis_apt_packages: []
travis_apt_sources: []

