# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.0.5
_src_path: https://github.com/OCA/oca-addons-repo-template.git
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: This repo holds addons developed to ease the development of REST
  and GraphQL services into Odoo.
repo_name: REST Framework
repo_slug: rest-framework
travis_apt_packages: []
travis_apt_sources: []
